- name: Eli
  specialty: Morphosyntax
  native: American English
  languages: 4-ish (English, Spanish, Japanese, Biblical Hebrew)
  bonus-q: What mergers do you have?
  bonus-a: Mary/merry/marry but not caught/cot or pin/pen
  mergers: Mary/merry/marry but not caught/cot or pin/pen
- name: Sarah
  specialty: Morphosyntax
  native: American English
  languages: 4-ish (English, Spanish, Japanese, Biblical Hebrew)
  bonus-q: What mergers do you have?
  bonus-a: Mary/merry/marry but not caught/cot or pin/pen
  mergers: Mary/merry/marry but not caught/cot or pin/pen
- name: Jenny
  specialty: Morphosyntax
  native: American English
  languages: 4-ish (English, Spanish, Japanese, Biblical Hebrew)
  bonus-q: What mergers do you have?
  bonus-a: Mary/merry/marry but not caught/cot or pin/pen
  mergers: Mary/merry/marry but not caught/cot or pin/pen
