- name: Eli
  specialty: Morphosyntax
  native: American English
  languages: Depends on how you count? English, Spanish, Japanese, some Biblical Hebrew, bits and pieces of other languages.
  accent: I've got Mary/merry/marry mergers but not caught/cot or pin/pen, plus Chicago final devoicing and some serious Northern Cities Shift.
  bonus-q: "Linguistics Hot Take:"
  bonus-a: All vowels are secretly the same vowel.

- name: Sarah
  specialty: Phonetics and etymology
  native: American English
  languages: \"Speak\"? Uhhhh... English, Latin, American Sign Language, French, and then bits and pieces of Spanish, Mandarin, Attic Greek, and probably others I'm forgetting.
  accent: Grew up with merry/Mary/marry, but am losing it (most likely to distinguish 'merry' of the lot); don't have cot/caught; sometimes have pin/pen; have half a Northern Cities Shift, a handful of New England vowels, and a hella lotta loose change, too.
  bonus-q: Favorite IPA symbol?
  bonus-a: I'm very fond of both ɬ and ɫ.

- name: Jenny
  specialty: Language evolution
  native: American English
  languages: English fluently, plus very beginner Japanese and a reasonable amount of Latin & ASL vocab but next to no grammar in either case (and my Latin pronunciation is both Ecclesiastical and partially forgotten).
  accent: I sound like I'm from somewhere you have friends but never where you're from yourself. Got the merry/Mary/marry merger (which I can kinda sorta distinguish sometimes but not consistently at all), but not caught/cot or pin/pen.
  bonus-q: Favorite IPA symbol?
  bonus-a: I’d have to go with either ð or ʃ.
